apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: niranjan/nodeapp:v1
      ports:
        - containerPort: 8080
    - name: nodeapp1
      image: lakshmi/nodeapp1:v1
      ports:
        - containerPort: 9090
